function vers = eegplugin_effectiveintervals (fig, try_strings, catch_strings);
vers = 'effectiveintervals1.0';

toolsmenu = findobj(fig, 'tag', 'tools');
calceffintscallback = [ 'calcparams = effectiveintervalsgui;' ...
                     'timeinterval = 0; eventtypes = {};' ...
                     'if length(calcparams) > 0' ...
                         'parsedinterval = str2num(calcparams.timeinterval);' ...
                         'if length(parsedinterval) > 0' ...
                            'timeinterval = parsedinterval(1);' ...
                         'end;' ...
                         'eventindexes = str2num(calcparams.eventtypes);' ...
                         'alltypes = getalleventtypes(EEG);' ...
                         'for i=1:length(eventindexes)' ...
                            'eventtypes(length(eventtypes)+1) = alltypes(eventindexes(i));' ...
                         'end;' ...
                         'clear parsedinterval;' ...
                         'clear eventindexes;' ...
                         'clear alltypes;' ...
                         'EFFINTS = calceffectiveintervals(EEG, eventtypes, timeinterval);' ... 
                     'end;' ...
                     'clear calcparams;' ... 
                     'clear timeinterval;' ...
                     'clear eventtypes;' ...
                     ];
uimenu( toolsmenu, 'Label', 'Calculate effective intervals', 'separator', 'on', 'CallBack', calceffintscallback);

plotmenu = findobj(fig, 'tag', 'plot');
uimenu( plotmenu, 'Label', 'Plot effective intervals', 'separator', 'on', 'CallBack', 'ploteffectiveintervals(EEG, EFFINTS)');