function[structout] = effectiveintervalsgui

    commandselectevents = [ 'tmpevents = getalleventtypes(EEG);' ...
                     'set(findobj(gcbf, ''tag'', ''eventtypes''), ''string'', ' ...
                     '       int2str(selectevents( tmpevents )));' ...
                     'clear tmpevents;' ];

    [res userdata err structout] = inputgui( 'geometry', { [1 0.2 1] [1 0.2 1] }, ...
        'geomvert', [1 1], 'uilist', { ...
        { 'Style', 'text', 'string', 'Time interval (ms):' } {}...
        { 'style', 'edit', 'string', '2000' 'tag' 'timeinterval'  }, ...
        { 'style', 'pushbutton' , 'string', 'Select events', 'callback', commandselectevents }, {}, ...
        { 'style', 'edit', 'string', '' 'tag' 'eventtypes'  } } );
    
end