function[structout] = selected_channels_gui

    commandchans = [ 'tmpchans = getallchannelnames(EEG);' ...
                     'set(findobj(gcbf, ''tag'', ''chantypes''), ''string'', ' ...
                     '       int2str(pop_chansel( tmpchans )));' ...
                     'clear tmpchans;' ];
                 
    [res userdata err structout] = inputgui( 'geometry', { [1 0.2 1] }, ...
        'geomvert', [1 1 1], 'uilist', { ...
        { 'style', 'pushbutton' , 'string', 'Select events', 'callback', commandchans }, {}, ...
        { 'style', 'edit', 'string', '' 'tag' 'chantypes'  } } );
    
end